In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('../data/raw/Zomato.csv')
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
df=data.copy()
print('Data Copy Successfully')

Data Copy Successfully

In [4]:
df.shape

(1000, 7)

In [5]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Cafe Vivacity,Yes,No,3.8/5,87,650,Cafes
1,Chatar Patar,No,No,3.7/5,59,330,Dining
2,Timepass Dinner,Yes,No,3.8/5,275,540,Buffet
3,T3H Cafe,No,No,3.9/5,85,300,Cafes
4,Faasos,Yes,No,4.2/5,385,500,other

In [6]:
df.duplicated().sum()

np.int64(220)

In [7]:
df = df.drop_duplicates(keep='first')
print("Duplicate Rows Deleted Succesfully")

Duplicate Rows Deleted Succesfully

In [8]:
# verify Duplicated
df.duplicated().sum()

np.int64(0)

In [9]:
df.shape

(780, 7)

In [10]:
df['rate']

0      3.8/5
1      3.7/5
2      3.8/5
3      3.9/5
4      4.2/5
       ...
992    3.0/5
994    4.1/5
995    3.4/5
996    4.0/5
997    3.2/5
Name: rate, Length: 780, dtype: str

In [11]:
# Replace '/5' with empty string
df["rate"] = df["rate"].str.replace("/5", "", regex=False)

In [12]:
#convert to numeric
df["rate"] = pd.to_numeric(df["rate"], errors="coerce")

In [13]:
df['rate']

0      3.8
1      3.7
2      3.8
3      3.9
4      4.2
      ...
992    3.0
994    4.1
995    3.4
996    4.0
997    3.2
Name: rate, Length: 780, dtype: float64

In [14]:
print(df['rate'].dtype)

float64

In [15]:
# check unique values for categorical columns
print(df["online_order"].unique())
print(df["book_table"].unique())
print(df["listed_in(type)"].unique())

<StringArray>
['Yes', 'No']
Length: 2, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
<StringArray>
['Cafes', 'Dining', 'Buffet', 'other']
Length: 4, dtype: str

In [16]:
df["rate"].describe()

count    780.000000
mean       3.694103
std        0.402261
min        2.600000
25%        3.400000
50%        3.800000
75%        4.000000
max        4.600000
Name: rate, dtype: float64

In [17]:
# check the rate is above 5
df[df["rate"] > 5]

Empty DataFrame
Columns: [name, online_order, book_table, rate, votes, approx_cost(for two people), listed_in(type)]
Index: []

In [18]:
# check the rate is below 5
df[df["rate"] < 0]

Empty DataFrame
Columns: [name, online_order, book_table, rate, votes, approx_cost(for two people), listed_in(type)]
Index: []

In [19]:
df.describe()

             rate        votes  approx_cost(for two people)
count  780.000000   780.000000                   780.000000
mean     3.694103   325.348718                   457.974359
std      0.402261   698.933899                   226.909808
min      2.600000     0.000000                    90.000000
25%      3.400000    22.000000                   270.000000
50%      3.800000    76.500000                   440.000000
75%      4.000000   306.000000                   635.000000
max      4.600000  5357.000000                  1040.000000

In [20]:
df = df.rename(columns={
    "approx_cost(for two people)": "approx_cost",
    "listed_in(type)": "restaurant_type"
})

In [21]:
for i in df.columns:
    print(i)

name
online_order
book_table
rate
votes
approx_cost
restaurant_type

In [22]:
# final data check
df.info()

<class 'pandas.DataFrame'>
Index: 780 entries, 0 to 997
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             780 non-null    str
 1   online_order     780 non-null    str
 2   book_table       780 non-null    str
 3   rate             780 non-null    float64
 4   votes            780 non-null    int64
 5   approx_cost      780 non-null    int64
 6   restaurant_type  780 non-null    str
dtypes: float64(1), int64(2), str(4)
memory usage: 48.8 KB

In [23]:
df.to_csv("../data/clean/Zomato_cleaned.csv", index=False)
print("Saved Successfully....!")

Saved Successfully....!